#!/usr/bin/env node
/**
 * inline-example.mjs — Build-time inliner for the example CSV (S03.8).
 *
 * Reads public/examples/sample.csv and writes a generated TypeScript
 * module src/lib/example-csv.generated.ts that exports the CSV as a
 * string constant. The deployed bundle carries the CSV inline; no
 * fetch call, no public/examples/sample.csv URL in dist/.
 *
 * The script is idempotent (no timestamps, no random suffixes) so
 * the generated module's contents are byte-identical across runs.
 *
 * Privacy Baseline: the script uses Node's filesystem APIs only
 * (readFileSync, writeFileSync). No network IO.
 *
 * Usage:
 *   node scripts/inline-example.mjs
 *
 * Wired into npm scripts:
 *   dev/build/test — runs before vite/vitest so the generated module
 *   exists when the rest of the pipeline imports it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const fixturePath = join(repoRoot, 'public', 'examples', 'sample.csv');
const generatedPath = join(
  repoRoot,
  'src',
  'lib',
  'example-csv.generated.ts',
);

/**
 * Escape a raw CSV string for embedding inside a TypeScript string
 * literal. Backslashes are doubled, lone `"` are escaped, and all
 * raw newlines become `\n` (the literal escape). The original byte
 * sequence round-trips through a TS parser unchanged.
 *
 * Exported for Vitest round-trip tests (Review #2 finding #4):
 * importing the function directly from the inliner source means a
 * drift in the inliner's escape logic flips the test, instead of the
 * test silently passing against a stale mirror copy.
 */
export function escapeForTsStringLiteral(raw) {
  return raw
    .replace(/\\/g, '\\\\') // backslash → \\
    .replace(/"/g, '\\"') // " → \"
    .replace(/\r\n/g, '\\r\\n') // CRLF → \r\n
    .replace(/\n/g, '\\n') // LF → \n
    .replace(/\r/g, '\\r'); // lone CR → \r
}

export function escapeForTsStringSingle(raw) {
  // For single-quoted literals: only ' and \ need escaping.
  return raw
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r\n/g, '\\r\\n')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

const raw = readFileSync(fixturePath, 'utf8');
const escaped = escapeForTsStringLiteral(raw);
const filenameEscaped = escapeForTsStringSingle('sample.csv');
const mimeEscaped = escapeForTsStringSingle('text/csv');

// Count rows (the header is row 1; data rows follow).
const rowCount = raw.split(/\r\n|\n/).filter((line) => line.length > 0).length;

const output = `// AUTO-GENERATED by scripts/inline-example.mjs — DO NOT EDIT BY HAND.
//
// This file is regenerated on every build / test / dev invocation
// from public/examples/sample.csv (the single source of truth).
// It is gitignored so contributors don't accidentally edit it; the
// upstream fixture is the only place to change the example CSV.
//
// The CSV is bundled inline (no fetch at runtime) per the Privacy
// Baseline (PRD FR-23). The deployed HTML/JS bundle carries the
// fixture as a string constant — no public/examples/sample.csv URL
// in dist/, no fetch call, no network IO.

export const SAMPLE_CSV: string = "${escaped}";
export const SAMPLE_CSV_FILENAME: string = '${filenameEscaped}';
export const SAMPLE_CSV_MIME: string = '${mimeEscaped}';
`;

writeFileSync(generatedPath, output, 'utf8');

// eslint-disable-next-line no-console
console.log(
  `[inline-example] wrote ${generatedPath.replace(repoRoot + '\\', '')} · ${raw.length} bytes · ${rowCount} rows`,
);
